name: 'dbt_ingestion'
version: '1.0.0'
config-version: 2
profile: 'snowflake_local'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  dbt_ingestion:
    +materialized: view
